### ISSUE TITLE
Upgrade kuberentes version to 1.13

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/kube-batch#542]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

As https://github.com/kubernetes/kubernetes/pull/72305 merged, it should be OK for us to upgrade k8s to 1.13 right now :)

**Comment by Jeffwan** [comment]
dep status 

```
PROJECT                                           CONSTRAINT                VERSION                   REVISION  LATEST   PKGS USED
......// only following libs are k8s.io
k8s.io/api                                        *                                                   9e32546            29
k8s.io/apiextensions-apiserver                    *                                                   bbc5246            6
k8s.io/apimachinery                               kubernetes-1.11.1-beta.0  kubernetes-1.11.1-beta.0  103fd09            46
k8s.io/apiserver                                  *                                                   13d596d            6
k8s.io/client-go                                  *                                                   e5bc2a7            131
k8s.io/gengo                                      *                                                   fdcf9f9            7
k8s.io/kube-openapi                               *                                                   91cfa47            1
k8s.io/kubernetes                                 *                                                   78d78e4            53
k8s.io/utils                                      *                                                   66066c8            1

```

Is this task to update all kubernetes related dependency to v1.13.1 (latest release I think)? I am trying to add constraints in Gopkg.toml and then `dep ensure -update`. but looks like there're some compatible issues.

**Comment by k82cn** [comment]
> Is this task to update all kubernetes related dependency to v1.13.1 (latest release I think)?

Yes, I think we need to upgrade all related dependency; mixed dependencies may have unexpected behaviour :)

**Comment by Jeffwan** [comment]
@k82cn  The upstream change is release in v1.13.2. I will directly upgrade to this version and resolve all breaking changes and conflicts. BTW, I am trying to understand if kube-batch has compatibility matrix. if dependencies is upgraded to v1.13.x, any issue with v1.12.x users?
