### ISSUE TITLE
Replace cmd/deepcopy-gen with binaries

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/kube-batch#972]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Currently, we use cmd/deepcopy-gen to generate deepcopy codes; it's better to replace such kind of source code with release of code-generators.

**Comment by Sajiyah-Salat** [comment]
Hello, Is this pr still relevant? If yes, can you provide me a detail

**Comment by mrbobbytables** [comment]
Repo is to be archived, for more information please see: https://github.com/kubernetes/org/issues/4200

/close
