### ISSUE TITLE
Update group name to scheduling.x-k8s.io

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/kube-batch#973]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

It's better to follow the practice for group name of k8s-sigs , e.g. `x-k8s.io`.

**Comment by moostoopha** [comment]
> **Is this a BUG REPORT or FEATURE REQUEST?**:
> 
> /kind feature
> 
> **What happened**:
> 
> It's better to follow the practice for group name of k8s-sigs , e.g. `x-k8s.io`.

can you Please give me some context and detail so i can help you to the point.

**Comment by kerthcet** [comment]
/assign
I'll push forward this.

**Comment by mrbobbytables** [comment]
Repo is to be archived, for more information please see: https://github.com/kubernetes/org/issues/4200

/close
